export type Mode = "in_person" | "online" | "hybrid" | "unknown";

export interface ProblemSource {
  kind: "inline" | "google_doc" | "pdf" | "external";
  title: string | null;
  url: string | null;
  text: string | null;
  status: "parsed" | "linked" | "unavailable";
}

export interface Hackathon {
  uid: string;
  source: string;
  source_id: string;
  title: string;
  url: string;
  tagline: string | null;
  excerpt?: string;
  starts_at: string | null;
  ends_at: string | null;
  reg_opens_at: string | null;
  reg_deadline: string | null;
  mode: Mode;
  city: string | null;
  country: string | null;
  organiser: string | null;
  prize_amount: number | null;
  prize_currency: string | null;
  themes: string[];
  tracks: string[];
  sponsors: string[];
  problem_sources: ProblemSource[];
  team_min: number | null;
  team_max: number | null;
  participants_count: number | null;
  domains: string[];
  /** Human-readable topic names, denormalised so search can match what a student types. */
  topic_labels: string[];
  /** Ideas themselves live in a separate file — see IdeaSet. */
  idea_count: number;
  /** First idea's title, shown on the card so the best content is not hidden behind a click. */
  idea_teaser: string | null;
  /** Public URL identity: /h/<slug>. Generated by the exporter; must stay stable. */
  slug: string;
}

/** Fetched from data/ideas/<uid>.json only when a card is opened. */
export interface IdeaSet {
  ideas: Idea[];
  exemplars: Exemplar[];
  grounding: Grounding;
}

export interface Idea {
  title: string;
  pitch: string;
  problem_statement?: string;
  why_it_could_win: string;
  stack: string[];
  track?: string;
  inspired_by: string[];
  build_hours?: number;
}

export interface Exemplar {
  uid: string;
  title: string;
  url: string;
  prize: string | null;
  hackathon_name: string | null;
  year: number | null;
  tech: string[];
}

export interface Grounding {
  exemplar_count: number;
  domains: string[];
  thin: boolean;
  patterns: string[];
  problem_source_count?: number;
  status?: "problem_grounded" | "theme_grounded" | "limited";
}

export interface Domain {
  id: string;
  label: string;
  count: number;
}

export interface Bundle {
  generated_at: string;
  count: number;
  domains: Domain[];
  hackathons: Hackathon[];
}

export interface Tool {
  name: string;
  url: string;
  what_you_get: string;
  caveat: string | null;
  free: boolean;
  checked: string;
  /** True when no human has confirmed the entry recently; the page says so rather than hiding it. */
  stale: boolean;
}

export interface ToolsBundle {
  categories: { id: string; label: string; tools: Tool[] }[];
  count: number;
  stale_after_days: number;
}
